### ISSUE TITLE
dashbase.sh does not work

### ISSUE THREAD

**Issue by ZongqiangZhang** [dashbase/dashbase-support#3]
log4j: setFile ended
log4j: Adding appender named [asyncInfoLog] to category [root].
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for java.lang.String annotated with @com.google.inject.name.Named(value=appName) was bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=appName)
    for field at rapid.metrics.MetricsReporterProvider.appName(MetricsReporterProvider.java:19)
  at io.dashbase.cmdline.RapidCommandLineApp$5.configure(RapidCommandLineApp.java:181)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at io.dashbase.cmdline.RapidCommandLineApp.buildInjector(RapidCommandLineApp.java:184)
        at io.dashbase.cmdline.RapidCommandLineApp.main(RapidCommandLineApp.java:203)

**Comment by javasoze** [comment]
fixed.
